const constants = {
  ADD_NOTE: "ADD_NOTE",
  REMOVE_NOTE: "REMOVE_NOTE",
  UPDATE_NOTE: "UPDATE_NOTE",
  // NOTE_SET_EDITABLE: "NOTE_SET_EDITABLE",
  NOTE_SET_ARCHIVED: "NOTE_SET_ARCHIVED",
  NOTE_SET_COMPLETED: "NOTE_SET_COMPLETED",
  FETCH_NOTES: "FETCH_NOTES",
  

  SHOW_ALL: 'SHOW_ALL',
  TOGGLE_VIEW: 'TOGGLE_VIEW',
  SHOW_ARCHIVE: 'SHOW_ARCHIVE',
  SHOW_NEW: 'SHOW_NEW',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
}

export default constants
